---
- name: (Ubuntu) install vncserver
  when: ansible_distribution == "Ubuntu"
  environment: proxy_env
  apt: name={{ item }}
  with_items:
    - gnome-core
    - xfce4
    - firefox
    - vnc4server

- name: (Fedora) install vncserver
  when: ansible_distribution == "Fedora"
  environment: proxy_env
  yum: name={{ item }}
  with_items:
    - tigervnc-server

- name: (Fedora) install vncserver systemd unit for arothste on port 5901
  when: ansible_distribution == "Fedora"
  copy: src='etc/systemd/system/vncserver@.service' dest='/etc/systemd/system/vncserver@.service'

- name: (Fedora) launch vncserver system unit for arothste on port 5901
  when: ansible_distribution == "Fedora"
  service: name=vncserver@:1.service enabled=yes state=started
  